[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "solady/=lib/solady/",
    "v3-core/=lib/v3-core/",
    "v3-periphery/=lib/v3-periphery/",
    "eigenlayer-middleware/=lib/eigenlayer-middleware/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
